// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app2.app2t.domain.pjm;

import com.app2.app2t.domain.pjm.ImportanceTask;
import com.app2.app2t.domain.pjm.ImportanceTaskDataOnDemand;
import com.app2.app2t.domain.pjm.ImportanceTaskIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ImportanceTaskIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ImportanceTaskIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ImportanceTaskIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ImportanceTaskIntegrationTest: @Transactional;
    
    @Autowired
    ImportanceTaskDataOnDemand ImportanceTaskIntegrationTest.dod;
    
    @Test
    public void ImportanceTaskIntegrationTest.testCountImportanceTasks() {
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to initialize correctly", dod.getRandomImportanceTask());
        long count = ImportanceTask.countImportanceTasks();
        Assert.assertTrue("Counter for 'ImportanceTask' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ImportanceTaskIntegrationTest.testFindImportanceTask() {
        ImportanceTask obj = dod.getRandomImportanceTask();
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to provide an identifier", id);
        obj = ImportanceTask.findImportanceTask(id);
        Assert.assertNotNull("Find method for 'ImportanceTask' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ImportanceTask' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ImportanceTaskIntegrationTest.testFindAllImportanceTasks() {
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to initialize correctly", dod.getRandomImportanceTask());
        long count = ImportanceTask.countImportanceTasks();
        Assert.assertTrue("Too expensive to perform a find all test for 'ImportanceTask', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ImportanceTask> result = ImportanceTask.findAllImportanceTasks();
        Assert.assertNotNull("Find all method for 'ImportanceTask' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ImportanceTask' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ImportanceTaskIntegrationTest.testFindImportanceTaskEntries() {
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to initialize correctly", dod.getRandomImportanceTask());
        long count = ImportanceTask.countImportanceTasks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ImportanceTask> result = ImportanceTask.findImportanceTaskEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ImportanceTask' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ImportanceTask' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ImportanceTaskIntegrationTest.testFlush() {
        ImportanceTask obj = dod.getRandomImportanceTask();
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to provide an identifier", id);
        obj = ImportanceTask.findImportanceTask(id);
        Assert.assertNotNull("Find method for 'ImportanceTask' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyImportanceTask(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ImportanceTask' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImportanceTaskIntegrationTest.testMergeUpdate() {
        ImportanceTask obj = dod.getRandomImportanceTask();
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to provide an identifier", id);
        obj = ImportanceTask.findImportanceTask(id);
        boolean modified =  dod.modifyImportanceTask(obj);
        Integer currentVersion = obj.getVersion();
        ImportanceTask merged = (ImportanceTask)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ImportanceTask' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImportanceTaskIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to initialize correctly", dod.getRandomImportanceTask());
        ImportanceTask obj = dod.getNewTransientImportanceTask(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ImportanceTask' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ImportanceTask' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ImportanceTaskIntegrationTest.testRemove() {
        ImportanceTask obj = dod.getRandomImportanceTask();
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImportanceTask' failed to provide an identifier", id);
        obj = ImportanceTask.findImportanceTask(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ImportanceTask' with identifier '" + id + "'", ImportanceTask.findImportanceTask(id));
    }
    
}
