// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app2.app2t.domain.pjm;

import com.app2.app2t.domain.pjm.OtherTask;
import com.app2.app2t.domain.pjm.OtherTaskDataOnDemand;
import com.app2.app2t.domain.pjm.TypeTaskDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OtherTaskDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OtherTaskDataOnDemand: @Component;
    
    private Random OtherTaskDataOnDemand.rnd = new SecureRandom();
    
    private List<OtherTask> OtherTaskDataOnDemand.data;
    
    @Autowired
    TypeTaskDataOnDemand OtherTaskDataOnDemand.typeTaskDataOnDemand;
    
    public OtherTask OtherTaskDataOnDemand.getNewTransientOtherTask(int index) {
        OtherTask obj = new OtherTask();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setDetail(obj, index);
        setEmpCode(obj, index);
        setProgress(obj, index);
        setStatus(obj, index);
        setTaskCost(obj, index);
        setTaskName(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void OtherTaskDataOnDemand.setCreatedBy(OtherTask obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void OtherTaskDataOnDemand.setCreatedDate(OtherTask obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void OtherTaskDataOnDemand.setDetail(OtherTask obj, int index) {
        String detail = "detail_" + index;
        if (detail.length() > 255) {
            detail = detail.substring(0, 255);
        }
        obj.setDetail(detail);
    }
    
    public void OtherTaskDataOnDemand.setEmpCode(OtherTask obj, int index) {
        String empCode = "empCode_" + index;
        if (empCode.length() > 15) {
            empCode = empCode.substring(0, 15);
        }
        obj.setEmpCode(empCode);
    }
    
    public void OtherTaskDataOnDemand.setProgress(OtherTask obj, int index) {
        Integer progress = new Integer(index);
        obj.setProgress(progress);
    }
    
    public void OtherTaskDataOnDemand.setStatus(OtherTask obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public void OtherTaskDataOnDemand.setTaskCost(OtherTask obj, int index) {
        Double taskCost = new Integer(index).doubleValue();
        if (taskCost > 9999999.9999D) {
            taskCost = 9999999.9999D;
        }
        obj.setTaskCost(taskCost);
    }
    
    public void OtherTaskDataOnDemand.setTaskName(OtherTask obj, int index) {
        String taskName = "taskName_" + index;
        if (taskName.length() > 40) {
            taskName = taskName.substring(0, 40);
        }
        obj.setTaskName(taskName);
    }
    
    public void OtherTaskDataOnDemand.setUpdatedBy(OtherTask obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void OtherTaskDataOnDemand.setUpdatedDate(OtherTask obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public OtherTask OtherTaskDataOnDemand.getSpecificOtherTask(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        OtherTask obj = data.get(index);
        Long id = obj.getId();
        return OtherTask.findOtherTask(id);
    }
    
    public OtherTask OtherTaskDataOnDemand.getRandomOtherTask() {
        init();
        OtherTask obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return OtherTask.findOtherTask(id);
    }
    
    public boolean OtherTaskDataOnDemand.modifyOtherTask(OtherTask obj) {
        return false;
    }
    
    public void OtherTaskDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = OtherTask.findOtherTaskEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'OtherTask' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<OtherTask>();
        for (int i = 0; i < 10; i++) {
            OtherTask obj = getNewTransientOtherTask(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
