// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app2.app2t.domain.pjm;

import com.app2.app2t.domain.pjm.OtherTaskDataOnDemand;
import com.app2.app2t.domain.pjm.Plan;
import com.app2.app2t.domain.pjm.PlanDataOnDemand;
import com.app2.app2t.domain.pjm.TaskDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PlanDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PlanDataOnDemand: @Component;
    
    private Random PlanDataOnDemand.rnd = new SecureRandom();
    
    private List<Plan> PlanDataOnDemand.data;
    
    @Autowired
    OtherTaskDataOnDemand PlanDataOnDemand.otherTaskDataOnDemand;
    
    @Autowired
    TaskDataOnDemand PlanDataOnDemand.taskDataOnDemand;
    
    public Plan PlanDataOnDemand.getNewTransientPlan(int index) {
        Plan obj = new Plan();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setDateEnd(obj, index);
        setDateStart(obj, index);
        setNote(obj, index);
        setStatus(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void PlanDataOnDemand.setCreatedBy(Plan obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void PlanDataOnDemand.setCreatedDate(Plan obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void PlanDataOnDemand.setDateEnd(Plan obj, int index) {
        Date dateEnd = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateEnd(dateEnd);
    }
    
    public void PlanDataOnDemand.setDateStart(Plan obj, int index) {
        Date dateStart = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateStart(dateStart);
    }
    
    public void PlanDataOnDemand.setNote(Plan obj, int index) {
        String note = "note_" + index;
        if (note.length() > 255) {
            note = note.substring(0, 255);
        }
        obj.setNote(note);
    }
    
    public void PlanDataOnDemand.setStatus(Plan obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public void PlanDataOnDemand.setUpdatedBy(Plan obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void PlanDataOnDemand.setUpdatedDate(Plan obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public Plan PlanDataOnDemand.getSpecificPlan(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Plan obj = data.get(index);
        Long id = obj.getId();
        return Plan.findPlan(id);
    }
    
    public Plan PlanDataOnDemand.getRandomPlan() {
        init();
        Plan obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Plan.findPlan(id);
    }
    
    public boolean PlanDataOnDemand.modifyPlan(Plan obj) {
        return false;
    }
    
    public void PlanDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Plan.findPlanEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Plan' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Plan>();
        for (int i = 0; i < 10; i++) {
            Plan obj = getNewTransientPlan(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
