// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app2.app2t.domain.pjm;

import com.app2.app2t.domain.pjm.TypeTask;
import com.app2.app2t.domain.pjm.TypeTaskDataOnDemand;
import com.app2.app2t.domain.pjm.TypeTaskIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TypeTaskIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TypeTaskIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TypeTaskIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TypeTaskIntegrationTest: @Transactional;
    
    @Autowired
    TypeTaskDataOnDemand TypeTaskIntegrationTest.dod;
    
    @Test
    public void TypeTaskIntegrationTest.testCountTypeTasks() {
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to initialize correctly", dod.getRandomTypeTask());
        long count = TypeTask.countTypeTasks();
        Assert.assertTrue("Counter for 'TypeTask' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TypeTaskIntegrationTest.testFindTypeTask() {
        TypeTask obj = dod.getRandomTypeTask();
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to provide an identifier", id);
        obj = TypeTask.findTypeTask(id);
        Assert.assertNotNull("Find method for 'TypeTask' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TypeTask' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TypeTaskIntegrationTest.testFindAllTypeTasks() {
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to initialize correctly", dod.getRandomTypeTask());
        long count = TypeTask.countTypeTasks();
        Assert.assertTrue("Too expensive to perform a find all test for 'TypeTask', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TypeTask> result = TypeTask.findAllTypeTasks();
        Assert.assertNotNull("Find all method for 'TypeTask' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TypeTask' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TypeTaskIntegrationTest.testFindTypeTaskEntries() {
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to initialize correctly", dod.getRandomTypeTask());
        long count = TypeTask.countTypeTasks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TypeTask> result = TypeTask.findTypeTaskEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TypeTask' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TypeTask' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TypeTaskIntegrationTest.testFlush() {
        TypeTask obj = dod.getRandomTypeTask();
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to provide an identifier", id);
        obj = TypeTask.findTypeTask(id);
        Assert.assertNotNull("Find method for 'TypeTask' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTypeTask(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TypeTask' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TypeTaskIntegrationTest.testMergeUpdate() {
        TypeTask obj = dod.getRandomTypeTask();
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to provide an identifier", id);
        obj = TypeTask.findTypeTask(id);
        boolean modified =  dod.modifyTypeTask(obj);
        Integer currentVersion = obj.getVersion();
        TypeTask merged = (TypeTask)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TypeTask' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TypeTaskIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to initialize correctly", dod.getRandomTypeTask());
        TypeTask obj = dod.getNewTransientTypeTask(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TypeTask' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'TypeTask' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TypeTaskIntegrationTest.testRemove() {
        TypeTask obj = dod.getRandomTypeTask();
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeTask' failed to provide an identifier", id);
        obj = TypeTask.findTypeTask(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TypeTask' with identifier '" + id + "'", TypeTask.findTypeTask(id));
    }
    
}
