// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app2.app2t.domain;

import com.app2.app2t.domain.ParameterDetailDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ParameterDetailDataOnDemand_Roo_Configurable {
    
    declare @type: ParameterDetailDataOnDemand: @Configurable;
    
}
